import {
  LayoutDashboard,
  BookOpen,
  Trophy,
  BarChart,
  MessageCircle,
  User,
  Leaf,
  Recycle,
  Droplets,
  Star,
  TreePine,
  Sprout,
  ChevronRight,
  LogIn,
  LogOut,
  Settings,
  Sun,
  Moon,
  Lightbulb,
  Upload,
  Loader,
  Sparkles,
  CheckCircle,
  AlertCircle,
  Zap,
  Calendar,
  Repeat,
  Award,
  Bolt,
  BookMarked,
  ShieldCheck,
  Users,
  Wind,
  Mail
} from 'lucide-react';

export const Icons = {
  layoutDashboard: LayoutDashboard,
  bookOpen: BookOpen,
  trophy: Trophy,
  barChart: BarChart,
  messageCircle: MessageCircle,
  user: User,
  leaf: Leaf,
  recycle: Recycle,
  droplets: Droplets,
  star: Star,
  treePine: TreePine,
  sprout: Sprout,
  chevronRight: ChevronRight,
  logIn: LogIn,
  logOut: LogOut,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  lightbulb: Lightbulb,
  upload: Upload,
  loader: Loader,
  sparkles: Sparkles,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  zap: Zap,
  calendar: Calendar,
  repeat: Repeat,
  award: Award,
  bolt: Bolt,
  bookMarked: BookMarked,
  shieldCheck: ShieldCheck,
  users: Users,
  wind: Wind,
  mail: Mail,
};
