
import {
  LayoutDashboard,
  BookOpen,
  Trophy,
  BarChart,
  MessageCircle,
  User,
  Leaf,
  Recycle,
  Droplets,
  Star,
  TreePine,
  Sprout,
  ChevronRight,
  LogIn,
  LogOut,
  Settings,
  Sun,
  Moon,
  Lightbulb,
  Upload,
  Loader,
  Sparkles,
  CheckCircle,
  AlertCircle,
  Zap,
  Calendar,
  Repeat,
  Award,
  Bolt,
  BookMarked,
  ShieldCheck,
  Users,
  Wind,
  Mail,
  Gift,
  School,
  ThumbsUp,
  Globe,
  Wallet,
  Book,
  Briefcase,
  Home,
  Mountain,
  HardHat,
  Heart,
  DollarSign,
  Bot,
  X,
  Send,
  Move,
  Trees,
} from 'lucide-react';

export const Icons = {
  layoutDashboard: LayoutDashboard,
  bookOpen: BookOpen,
  trophy: Trophy,
  barChart: BarChart,
  messageCircle: MessageCircle,
  user: User,
  leaf: Leaf,
  recycle: Recycle,
  droplets: Droplets,
  star: Star,
  treePine: TreePine,
  sprout: Sprout,
  chevronRight: ChevronRight,
  logIn: LogIn,
  logOut: LogOut,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  lightbulb: Lightbulb,
  upload: Upload,
  loader: Loader,
  sparkles: Sparkles,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  zap: Zap,
  calendar: Calendar,
  repeat: Repeat,
  award: Award,
  bolt: Bolt,
  bookMarked: BookMarked,
  shieldCheck: ShieldCheck,
  users: Users,
  wind: Wind,
  mail: Mail,
  gift: Gift,
  school: School,
  thumbsUp: ThumbsUp,
  globe: Globe,
  wallet: Wallet,
  book: Book,
  briefcase: Briefcase,
  home: Home,
  mountain: Mountain,
  teacherAssistant: HardHat,
  community: Users,
  economy: DollarSign,
  heart: Heart,
  bot: Bot,
  x: X,
  send: Send,
  move: Move,
  ecoVillage: Trees
};

    