import {
  LayoutDashboard,
  BookOpen,
  Trophy,
  BarChart,
  MessageCircle,
  User,
  Leaf,
  Recycle,
  Droplets,
  Star,
  TreePine,
  Sprout,
  ChevronRight,
  LogIn,
  LogOut,
  Settings,
  Sun,
  Moon,
  Lightbulb,
} from 'lucide-react';

export const Icons = {
  layoutDashboard: LayoutDashboard,
  bookOpen: BookOpen,
  trophy: Trophy,
  barChart: BarChart,
  messageCircle: MessageCircle,
  user: User,
  leaf: Leaf,
  recycle: Recycle,
  droplets: Droplets,
  star: Star,
  treePine: TreePine,
  seedling: Sprout,
  chevronRight: ChevronRight,
  logIn: LogIn,
  logOut: LogOut,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  lightbulb: Lightbulb,
};
